<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\CompanyCreationTask;
use App\Models\Cabinet;
use App\Models\User;

class CompanyCreationTaskSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cabinets = Cabinet::with('users')->get();

        if ($cabinets->isEmpty()) {
            $this->command->error('❌ Aucun cabinet trouvé. Exécutez d\'abord CabinetSeeder.');
            return;
        }

        $tasks = [
            [
                'cabinet_id' => $cabinets->first()->id,
                'user_id' => $cabinets->first()->users()->first()?->id,
                'company_name' => 'Green Morocco SARL',
                'company_type' => 'SARL',
                'client_name' => 'Mohammed Alami',
                'client_phone' => '+212 6 12 34 56 78',
                'client_email' => 'mohammed.alami@email.com',
                'activity_description' => 'Import et distribution de produits écologiques',
                'capital_social' => 100000,
                'status' => 'in_progress',
                'stage' => 'certificat_negatif',
                'certificat_negatif_done' => false,
                'statuts_done' => false,
                'capital_deposited' => false,
                'siege_address' => 'Boulevard Mohammed V, Immeuble Crystal',
                'siege_city' => 'Casablanca',
                'domiciliation_type' => 'domiciliation',
                'target_completion_date' => now()->addDays(14),
                'notes' => 'Client pressé, priorité haute',
                'position' => 1,
            ],
            [
                'cabinet_id' => $cabinets->first()->id,
                'user_id' => $cabinets->first()->users()->first()?->id,
                'company_name' => 'Tech Innovation SA',
                'company_type' => 'SA',
                'client_name' => 'Sarah Benjelloun',
                'client_phone' => '+212 6 98 76 54 32',
                'client_email' => 'sarah.benjelloun@techinnov.ma',
                'activity_description' => 'Développement de solutions logicielles sur mesure',
                'capital_social' => 300000,
                'status' => 'in_progress',
                'stage' => 'statuts',
                'certificat_negatif_done' => true,
                'certificat_negatif_date' => now()->subDays(5),
                'certificat_negatif_number' => 'CN2024-1234',
                'statuts_done' => false,
                'capital_deposited' => false,
                'siege_address' => 'Technopark, Bureau 205',
                'siege_city' => 'Rabat',
                'domiciliation_type' => 'bail',
                'target_completion_date' => now()->addDays(20),
                'notes' => 'Société de technologie, besoin de clauses spécifiques dans les statuts',
                'position' => 2,
            ],
            [
                'cabinet_id' => $cabinets->first()->id,
                'user_id' => $cabinets->first()->users()->skip(1)->first()?->id,
                'company_name' => 'Atlas Construction SARL',
                'company_type' => 'SARL',
                'client_name' => 'Ahmed Tazi',
                'client_phone' => '+212 6 55 44 33 22',
                'client_email' => 'ahmed.tazi@atlasconstruction.ma',
                'activity_description' => 'Entreprise de construction et travaux publics',
                'capital_social' => 500000,
                'status' => 'waiting_client',
                'stage' => 'capital_deposit',
                'certificat_negatif_done' => true,
                'certificat_negatif_date' => now()->subDays(10),
                'certificat_negatif_number' => 'CN2024-1235',
                'statuts_done' => true,
                'statuts_date' => now()->subDays(3),
                'capital_deposited' => false,
                'bank_name' => 'Attijariwafa Bank',
                'siege_address' => 'Zone Industrielle Ain Sebaa',
                'siege_city' => 'Casablanca',
                'domiciliation_type' => 'propriete',
                'target_completion_date' => now()->addDays(10),
                'notes' => 'En attente du dépôt de capital par le client',
                'position' => 3,
            ],
            [
                'cabinet_id' => $cabinets->skip(1)->first()->id,
                'user_id' => $cabinets->skip(1)->first()->users()->first()?->id,
                'company_name' => 'Marrakech Tours SAS',
                'company_type' => 'SAS',
                'client_name' => 'Yasmine El Fassi',
                'client_phone' => '+212 6 77 88 99 00',
                'client_email' => 'yasmine@marrakech-tours.ma',
                'activity_description' => 'Agence de voyages et organisation d\'événements',
                'capital_social' => 200000,
                'status' => 'in_progress',
                'stage' => 'enregistrement',
                'certificat_negatif_done' => true,
                'certificat_negatif_date' => now()->subDays(15),
                'certificat_negatif_number' => 'CN2024-1236',
                'statuts_done' => true,
                'statuts_date' => now()->subDays(8),
                'capital_deposited' => true,
                'capital_deposit_date' => now()->subDays(2),
                'bank_name' => 'BMCE Bank',
                'enregistrement_done' => false,
                'siege_address' => 'Avenue Mohammed VI, Guéliz',
                'siege_city' => 'Marrakech',
                'domiciliation_type' => 'bail',
                'target_completion_date' => now()->addDays(7),
                'notes' => 'Procédure d\'enregistrement en cours',
                'position' => 1,
            ],
            [
                'cabinet_id' => $cabinets->skip(1)->first()->id,
                'user_id' => $cabinets->skip(1)->first()->users()->first()?->id,
                'company_name' => 'Bio Farm SARL',
                'company_type' => 'SARL',
                'client_name' => 'Khalid Berrada',
                'client_phone' => '+212 6 11 22 33 44',
                'client_email' => 'khalid.berrada@biofarm.ma',
                'activity_description' => 'Production et commercialisation de produits biologiques',
                'capital_social' => 150000,
                'status' => 'waiting_admin',
                'stage' => 'rc_immatriculation',
                'certificat_negatif_done' => true,
                'certificat_negatif_date' => now()->subDays(20),
                'certificat_negatif_number' => 'CN2024-1237',
                'statuts_done' => true,
                'statuts_date' => now()->subDays(12),
                'capital_deposited' => true,
                'capital_deposit_date' => now()->subDays(7),
                'bank_name' => 'Crédit du Maroc',
                'enregistrement_done' => true,
                'enregistrement_date' => now()->subDays(4),
                'patente_done' => true,
                'patente_number' => 'PAT2024-5678',
                'identifiant_fiscal' => 'IF2024-9012',
                'rc_done' => false,
                'siege_address' => 'Route de l\'Ourika, Km 15',
                'siege_city' => 'Marrakech',
                'domiciliation_type' => 'propriete',
                'target_completion_date' => now()->addDays(5),
                'notes' => 'En attente de l\'immatriculation au RC par le tribunal',
                'position' => 2,
            ],
            [
                'cabinet_id' => $cabinets->first()->id,
                'user_id' => $cabinets->first()->users()->first()?->id,
                'company_name' => 'Express Logistics SASU',
                'company_type' => 'SASU',
                'client_name' => 'Pierre Dubois',
                'client_phone' => '+212 6 66 55 44 33',
                'client_email' => 'p.dubois@express-logistics.ma',
                'activity_description' => 'Services de transport et logistique express',
                'capital_social' => 50000,
                'status' => 'completed',
                'stage' => 'finalization',
                'certificat_negatif_done' => true,
                'certificat_negatif_date' => now()->subDays(30),
                'certificat_negatif_number' => 'CN2024-1238',
                'statuts_done' => true,
                'statuts_date' => now()->subDays(25),
                'capital_deposited' => true,
                'capital_deposit_date' => now()->subDays(20),
                'bank_name' => 'Société Générale',
                'enregistrement_done' => true,
                'enregistrement_date' => now()->subDays(15),
                'patente_done' => true,
                'patente_number' => 'PAT2024-5679',
                'identifiant_fiscal' => 'IF2024-9013',
                'rc_done' => true,
                'rc_number' => 'RC2024-3456',
                'rc_date' => now()->subDays(10),
                'cnss_done' => true,
                'cnss_number' => 'CNSS2024-7890',
                'cnss_date' => now()->subDays(5),
                'publication_done' => true,
                'publication_jal_date' => now()->subDays(3),
                'publication_bo_date' => now()->subDays(2),
                'siege_address' => 'Zone Franche, Lot 45',
                'siege_city' => 'Tanger',
                'domiciliation_type' => 'domiciliation',
                'target_completion_date' => now()->subDays(1),
                'actual_completion_date' => now()->subDays(1),
                'notes' => 'Société créée avec succès. Tous les documents remis au client.',
                'position' => 1,
            ],
            [
                'cabinet_id' => $cabinets->skip(2)->first()->id,
                'user_id' => $cabinets->skip(2)->first()->users()->first()?->id,
                'company_name' => 'Artisan Plus Auto-Entrepreneur',
                'company_type' => 'AUTO',
                'client_name' => 'Fatima Zahra',
                'client_phone' => '+212 6 99 88 77 66',
                'client_email' => 'fatima.zahra@artisanplus.ma',
                'activity_description' => 'Création et vente d\'articles artisanaux',
                'capital_social' => 0,
                'status' => 'draft',
                'stage' => 'initial_contact',
                'certificat_negatif_done' => false,
                'statuts_done' => false,
                'capital_deposited' => false,
                'siege_address' => 'Médina de Fès',
                'siege_city' => 'Fès',
                'domiciliation_type' => 'domiciliation',
                'target_completion_date' => now()->addDays(30),
                'notes' => 'Premier contact établi, en attente des documents du client',
                'position' => 1,
            ],
            [
                'cabinet_id' => $cabinets->first()->id,
                'user_id' => $cabinets->first()->users()->first()?->id,
                'company_name' => 'Digital Agency SNC',
                'company_type' => 'SNC',
                'client_name' => 'Omar & Samir Associates',
                'client_phone' => '+212 6 12 23 34 45',
                'client_email' => 'contact@digital-agency.ma',
                'activity_description' => 'Agence de communication digitale et marketing',
                'capital_social' => 80000,
                'status' => 'cancelled',
                'stage' => 'certificat_negatif',
                'certificat_negatif_done' => false,
                'statuts_done' => false,
                'capital_deposited' => false,
                'siege_address' => 'Quartier Palmier',
                'siege_city' => 'Casablanca',
                'domiciliation_type' => 'bail',
                'target_completion_date' => now()->addDays(15),
                'notes' => 'Projet annulé par le client - changement de stratégie',
                'position' => 99,
            ],
        ];

        foreach ($tasks as $taskData) {
            CompanyCreationTask::create($taskData);
        }

        $this->command->info('✅ Tâches de création de sociétés créées avec succès!');
        $this->command->info('📊 Résumé des tâches créées:');
        $this->command->line('   • 2 tâches en cours');
        $this->command->line('   • 1 tâche en attente client');
        $this->command->line('   • 1 tâche en attente administration');
        $this->command->line('   • 1 tâche terminée');
        $this->command->line('   • 1 tâche en brouillon');
        $this->command->line('   • 1 tâche annulée');
    }
}
